apiVersion: v1
kind: Secret
metadata:
  name: {{ include "binary-build.fullname" . }}-registry
  labels:
{{ include "binary-build.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}